Implemented run_existing_job.
No passing on of jobsfolder to symlinkInJobsFolder.

diff --git a/.local/bin/fb/fbctl b/.local/bin/fb/fbctl
--- a/.local/bin/fb/fbctl
+++ b/.local/bin/fb/fbctl
@@ -399,8 +399,6 @@ for help.\nTerminating..."
 fi
 # what to do when args_needed = 2?
 
-source ~/wrk/FB/.local/bin/fb/loc_param.sh
-
 err() {
   echo -e >&2 "$PNAME/${FUNCNAME[$1]} : $2\nTerminating"
 }
@@ -416,6 +414,94 @@ nrargs() {
   return 0
 }
 
+# symlinkInJobsFolder()
+# We figure out if whatever is passed as the location represents a symlink
+# in the current jobs folder.
+# PARAMETERS: backupscheme, location_parameter
+#
+# ALGORITHM:
+# we check if the given parameter exists
+#
+#   if it doesn't:
+#     does it exist within the job folder?
+#       return it, or give error message
+#   if it does
+#     we get the full path
+#     not a symlink?
+#       we convert to symlinkname
+#       does it exist within jobfolder?
+#         return it, or give error message
+#     it was a symlink:
+#       does it exist within jobsfolder?
+#         return it, or give error message
+#
+# RETURNS: A valid symlink, with full path, if any.
+
+# Does the file exist? if not, we might use the  jobs folder as a second chance
+symlinkInJobsFolder() {
+
+LDBG=1
+  if ! nrargs 2 $#  "I need two arguments!" ; then
+    exit 2
+  fi
+
+  backup_scheme="${1}"
+  loc_param="${2}"
+  jobs_folder="$XDG_DATA_HOME"/fbjobs/"$backup_scheme"
+
+  echo >&2 BackupScheme : "$backup_scheme"
+  echo >&2 JobsFolder : "$jobs_folder"
+
+  if [[ ! -r "$loc_param" ]] ; then
+    echo >&2 "$loc_param" : not found.
+   candidate="$jobs_folder"/"$loc_param"
+   echo >&2 "and the candidate is: $candidate"
+
+    if [[ ! -r "$candidate" ]] ; then
+        err 1 "$candidate doesn't exist, unresolvable conflict.\n\
+  Please specify another parameter."
+        exit 2
+    else
+      echo >&2 "found $candidate"
+      if ! isASymlink "$candidate" ; then
+        err 1 "$candidate isn't a symlink, unresolvable conflict.\n\
+  Please specify another parameter."
+        exit 2
+      else
+        echo "$candidate"
+      fi
+    fi
+  else
+    if [[ $LDBG -eq 0 ]] ; then echo >&2 " the parameter existed" ; fi
+
+    #  we get the real path
+    full_path="$(realpath "$loc_param")"
+    # we create a symlink of it.
+    if ! isASymlink "$full_path" ; then
+      # we need to create its symlink
+      symlinkName="$(fullPathSymlinkName "$full_path")"
+      if [[ $LDBG -eq 0 ]] ; then echo >&2 "Da symlinkname: $symlinkName" ; fi
+      candidate="$jobs_folder"/"$symlinkName"
+      if [[ ! -r "$candidate" ]] ; then
+        err 1 "$loc_param  isn't a backup job!"
+        exit 2
+      else
+        echo "$candidate"
+      fi
+    else
+      candidate="$full_path"
+      probe=${candidate/$jobs_folder/}
+      if [[ $LDBG -eq 0 ]] ; then echo >&2 Probe : $probe ; fi
+      if [[ "$probe" !=  "$candidate" ]] ; then
+        # its within, and a valid symlink
+        echo $candidate
+      else
+        err 1 "the symlink given is not the correct one for the path given"
+        exit 2
+      fi
+    fi
+  fi
+}
 # activateJob()
 # removes the paused state of a job.
 
@@ -608,9 +694,15 @@ execute_job_directly() {
 
   exit_code=0
   trap '' ERR
-  # shellcheck disable=SC2086 # No quoting of options!
-  "$backup_script" "$backup_scheme" "$symlink_name"
-  exit_code=$?
+  if [[ "$sub_command" == "run" && $DRY_RUN == true ]] ; then   
+    # shellcheck disable=SC2086 # No quoting of options!
+    "$backup_script" "$backup_scheme" "$symlink_name" --dry-run
+    exit_code=$?
+  else
+    # shellcheck disable=SC2086 # No quoting of options!
+    "$backup_script" "$backup_scheme" "$symlink_name"
+    exit_code=$?
+  fi
 
   if [[ $VERBOSE = true || $DEBUG -eq 0 || $DRY_RUN = true ]] ; then
     if [[ $exit_code -eq 0 ]] ; then
@@ -820,8 +912,46 @@ install_new_job() {
 
 }
 
+# run_existing_job() 
+# Difference between this, and start --now:
+# We're not executing through the governor anyway,
+# so, we're not considering any pause files and such.
+# But, we were supposed to consider dry-run on this one, because
+# on of the uses of this one, is for testing exclude files and such.
+# -We can just pass along the dry-run option on this one, as we could
+# on the the other one?
+# or this one could be named dry-run?
+
 run_existing_job() {
-  echo Stub..
+  set -e
+  if ! nrargs 2 $#  "I need two arguments!" ; then
+    exit 2
+  fi
+
+  # err 1 "Faking a start  of $1 $2 "
+  backup_scheme="$1"
+  location_parameter="$2"
+  jobs_folder="$XDG_DATA_HOME"/fbjobs/"$backup_scheme"
+
+  valid_symlink="$(symlinkInJobsFolder $backup_scheme "$location_parameter" )"
+  # valid_symlink="$(symlinkInJobsFolder $backup_scheme "$location_parameter" "$jobs_folder" )"
+
+  # TODO: Assert backup container exists
+  scheme_container="$( assertSchemeContainer "$backup_scheme" )"
+
+  # runner, a dumbed down version of governor,
+  # using the same stuff as fbrestore to figure
+  # which scheme we should use to to make the
+  # manager look for stuff.
+
+  just_symlink_name="$(justSymlinkName "$valid_symlink")"
+  # Need to find the symlink-name we're doing a lot twice.
+
+  assertBackupContainer "$backup_scheme" "$scheme_container"  "$just_symlink_name"
+  # We assert the Backucontainer is there, in case it is the first time.
+
+  execute_job_directly "$backup_scheme"  "$just_symlink_name" run
+
 }
 
 # edit_existing_job() 
