Redirect all error messages to stderr.

diff --git a/.local/bin/fb/fbsnapshot b/.local/bin/fb/fbsnapshot
--- a/.local/bin/fb/fbsnapshot
+++ b/.local/bin/fb/fbsnapshot
@@ -19,7 +19,7 @@ trap 'err_report $LINENO' ERR
 # TODO: Think of modus.
 dieIfCantSourceShellLibrary() {
   if [[ $# -ne 1 ]] ; then
-    echo -e "$PNAME/${FUNCNAME[0]} : Need an\
+    echo -e >&2 "$PNAME/${FUNCNAME[0]} : Need an\
     argument, an existing fb shell library file!\nTerminates..." >&2
     exit 5
   fi
@@ -28,7 +28,7 @@ dieIfCantSourceShellLibrary() {
     source "${1}"
   #  source "$fpth"/service_functions.sh
   else
-    echo -e  "$PNAME/${FUNCNAME[0]} : Can't find/source: ${1}\
+    echo -e >&2 "$PNAME/${FUNCNAME[0]} : Can't find/source: ${1}\
       \nTerminates... " >&2
     exit 255
   fi
@@ -104,7 +104,7 @@ consoleFBfolderIsMounted OneShot
 GETOPT_COMPATIBLE=true
 
 if [[ $# -eq 0 ]] ; then
-  echo -e "$PNAME : Too few arguments. At least I need a path to a directory,\
+  echo -e >&2 "$PNAME : Too few arguments. At least I need a path to a directory,\
     I should make a backup of.\nExecute \"$PNAME -h\" for help.\
     Terminating..."
  exit 2
@@ -138,8 +138,7 @@ TEMP=$(getopt -o chnvV --longoptions create-exclude-file,help,dry-run,verbose,ve
 
 # shellcheck disable=SC2181
 if [[ $? != 0 ]] ; then
-  echo >/dev/ttyBiscuits in the Attic
-  echo "$PNAME -h | --help for help :  Terminating..."
+  echo >&2 "$PNAME -h | --help for help :  Terminating..."
   exit 2
 fi
 
@@ -170,7 +169,7 @@ done
 # We need to collect the options we should pass along.
 
 if [[ $# -ne 1 ]] ; then
-    echo -e "$PNAME: I didn't get a mandatory parameter. A source-folder to \
+    echo -e >&2 "$PNAME: I didn't get a mandatory parameter. A source-folder to \
       back up.\n\"$PNAME -h\" for help.\nTerminating..."
     exit 2
 fi
@@ -191,11 +190,11 @@ fi
 SOURCE_FOLDER=$(realpath "$1")
 
 if [[ $DEBUG -eq 0  || $VERBOSE = true ]] ; then
-  echo "$PNAME : SOURCE_FOLDER: $SOURCE_FOLDER"
+  echo >&2 "$PNAME : SOURCE_FOLDER: $SOURCE_FOLDER"
 fi
 
 if [[ ! -d $SOURCE_FOLDER ]] ; then
-  echo "$PNAME : $SOURCE_FOLDER isn't a directory. Terminating..."
+  echo >&2 "$PNAME : $SOURCE_FOLDER isn't a directory. Terminating..."
   exit 1
 fi
 
@@ -204,12 +203,12 @@ fi
 SYMLINK_NAME=$(fullPathSymlinkName "$1")
 
 if [[ $DEBUG -eq 0 || $VERBOSE = true ]] ; then
-  echo "$PNAME : SYMLINK_NAME: $SYMLINK_NAME."
+  echo >&2 "$PNAME : SYMLINK_NAME: $SYMLINK_NAME."
 fi
 
 BACKUP_CONTAINER=$FB/OneShot/$SYMLINK_NAME
 if [[ $DEBUG -eq 0 || $VERBOSE = true ]] ; then
-  echo "$PNAME : Backups of $SOURCE_FOLDER are stored in: $BACKUP_CONTAINER"
+  echo >&2  "$PNAME : Backups of $SOURCE_FOLDER are stored in: $BACKUP_CONTAINER"
 fi
 
 # can be called from the OneShot routine.
@@ -221,12 +220,12 @@ if [[ ! -d "$BACKUP_CONTAINER" ]] ; then
   # selv om det er DRYRUN så beholder vi denne!
   mkdir -p "$BACKUP_CONTAINER"
   if [[ $DEBUG -eq 0 || $VERBOSE = true ]] ; then
-    echo -e "$PNAME : BACKUP_CONTAINER: $BACKUP_CONTAINER didn\'t exist.\
+    echo -e >&2 "$PNAME : BACKUP_CONTAINER: $BACKUP_CONTAINER didn\'t exist.\
       \nMaking $BACKUP_CONTAINER."
   fi
 else
   if [[ $DEBUG -eq 0 || $VERBOSE = true ]] ; then
-    echo "$PNAME : BACKUP_CONTAINER: $BACKUP_CONTAINER DID  exist."
+    echo >&2 "$PNAME : BACKUP_CONTAINER: $BACKUP_CONTAINER DID  exist."
   fi
 fi
 
@@ -235,7 +234,7 @@ TODAYS_BACKUP_FOLDER="$BACKUP_CONTAINER"/"$(baseNameDateStamped "$SYMLINK_NAME")
 CREATED_TODAYS_BACKUP_FOLDER=1
 if [[ ! -d "$TODAYS_BACKUP_FOLDER" ]] ; then
   if [[ $DEBUG -eq 0 || $VERBOSE = true  && $DRYRUN = false ]] ; then
-    echo -e "$PNAME : TODAYS_BACKUP_FOLDER: $TODAYS_BACKUP_FOLDER didn't \
+    echo -e >&2 "$PNAME : TODAYS_BACKUP_FOLDER: $TODAYS_BACKUP_FOLDER didn't \
       exist. Creating it:\nmkdir -p $TODAYS_BACKUP_FOLDER."
   fi
   if [[ $DRYRUN = false ]] ; then
@@ -243,12 +242,12 @@ if [[ ! -d "$TODAYS_BACKUP_FOLDER" ]] ; then
     mkdir -p "$TODAYS_BACKUP_FOLDER"
   else
     CREATED_TODAYS_BACKUP_FOLDER=0
-    echo -e  "$PNAME : Todays backup folder didn't exist, creating it:\n \
+    echo -e  >&2 "$PNAME : Todays backup folder didn't exist, creating it:\n \
       mkdir -p $TODAYS_BACKUP_FOLDER"
   fi
 else
   if [[ $DEBUG -eq 0 || $VERBOSE = true ]] ; then
-    echo -e  "$PNAME : TODAYS_BACKUP_FOLDER: $TODAYS_BACKUP_FOLDER DID \
+    echo -e  >&2 "$PNAME : TODAYS_BACKUP_FOLDER: $TODAYS_BACKUP_FOLDER DID \
       exist."
   fi
 fi
@@ -272,7 +271,7 @@ else
 fi
 
 if [[ $VERBOSE = true || $DEBUG -eq 0 || $DRYRUN = true ]] ; then
-  echo -e "$PNAME : EXECUTING:\n $BACKUP_SCRIPT $BACKUP_OPTIONS  \
+  echo -e >&2 "$PNAME : EXECUTING:\n $BACKUP_SCRIPT $BACKUP_OPTIONS  \
     $SOURCE_FOLDER  $TODAYS_BACKUP_FOLDER"
 fi
 
@@ -285,15 +284,15 @@ EXIT_STATUS=$?
 
 # We do some cleanup in OneShot.backup.sh
 if [[ $EXIT_STATUS -eq 0 &&  $DRYRUN = false  ]] ; then
-   echo  -e "$PNAME : backup  of $SOURCE_FOLDER into $TODAYS_BACKUP_FOLDER \
+   echo  -e >&2 "$PNAME : backup  of $SOURCE_FOLDER into $TODAYS_BACKUP_FOLDER \
      complete!"   | journalThis 5 OneShot
 
 elif [[ $EXIT_STATUS -gt 1 ]] ; then
 
   if [[ $EXIT_STATUS -eq 130 ]] ; then
-      echo "$PNAME : User interrupted the operation"
+      echo >&2 "$PNAME : User interrupted the operation"
   else
-      echo "$PNAME : A fatal error occurred."
+      echo >&2 "$PNAME : A fatal error occurred."
   fi
 
   if [[  -d "$TODAYS_BACKUP_FOLDER" && \
@@ -301,12 +300,12 @@ elif [[ $EXIT_STATUS -gt 1 ]] ; then
 
     if [[ $DRYRUN = false ]] ; then
       if [[ $VERBOSE = true || $DEBUG -eq 0 ]] ; then
-        echo -e "$PNAME : Removing todays backup folder due to fatal errors:\
+        echo -e >&2 "$PNAME : Removing todays backup folder due to fatal errors:\
           \n rm -fr $TODAYS_BACKUP_FOLDER"
       fi
       rm -fr "$TODAYS_BACKUP_FOLDER"
     else
-      echo -e "$PNAME : Removing todays backup folder due to fatal errors:\
+      echo -e >&2 "$PNAME : Removing todays backup folder due to fatal errors:\
         \n rm -fr $TODAYS_BACKUP_FOLDER"
     fi
   fi
